from typing import Any, Optional

def bisect_left_with_key(
    sequence: Any, value: Any, key: Optional[Any] = ...
): ...
def bisect_right_with_key(
    a: Any, x: Any, key: Any, lo: int = ..., hi: Optional[Any] = ...
): ...
