# pylint: disable=all
# flake8: noqa
from collections import namedtuple
from typing import Any

from beancount.core import data as data
from beancount.core.data import Price as Price

CompareError = namedtuple("CompareError", "source message entry")
IGNORED_FIELD_NAMES: Any

def stable_hash_namedtuple(objtuple: Any, ignore: Any = ...): ...
def hash_entry(entry: Any): ...
def hash_entries(entries: Any): ...
def compare_entries(entries1: Any, entries2: Any): ...
def includes_entries(subset_entries: Any, entries: Any): ...
def excludes_entries(subset_entries: Any, entries: Any): ...
