# pylint: disable=all
# flake8: noqa
from typing import Any

from beancount.core.data import Directive
from beancount.core.data import Entries

# def stable_hash_namedtuple(objtuple: Any, ignore: Any = ...): ...
def hash_entry(entry: Directive): ...
def hash_entries(entries: Entries): ...
def compare_entries(entries1: Entries, entries2: Entries): ...

# def includes_entries(subset_entries: Any, entries: Any): ...
# def excludes_entries(subset_entries: Any, entries: Any): ...
