# pylint: disable=missing-docstring,unused-argument,multiple-statements
from beancount.core.data import Directive
from beancount.core.data import Entries

# def stable_hash_namedtuple(objtuple: Any, ignore: Any = ...): ...
def hash_entry(entry: Directive) -> str: ...
def hash_entries(entries: Entries) -> str: ...
def compare_entries(entries1: Entries, entries2: Entries) -> bool: ...

# def includes_entries(subset_entries: Any, entries: Any): ...
# def excludes_entries(subset_entries: Any, entries: Any): ...
