# pylint: disable=all
# flake8: noqa
from typing import Any

class Distribution:
    hist: Any = ...
    def __init__(self) -> None: ...
    def empty(self): ...
    def update(self, value: Any) -> None: ...
    def min(self): ...
    def max(self): ...
    def mode(self): ...
