# pylint: disable=all
# flake8: noqa
FLAG_OKAY: str
FLAG_WARNING: str
FLAG_PADDING: str
FLAG_SUMMARIZE: str
FLAG_TRANSFER: str
FLAG_CONVERSIONS: str
FLAG_UNREALIZED: str
FLAG_RETURNS: str
FLAG_MERGING: str
