import type { StreamParser, StringStream } from "@codemirror/language";

// Import the autogenerated (by a script in the 'contrib' directory) lists
import bql_grammar from "./bql-grammar.ts";

interface BqlParserState {
  block_comment: boolean;
  terminated: boolean;
}

const keywords = new Set(bql_grammar.keywords);
const columns = new Set(bql_grammar.columns);
const functions = new Set(bql_grammar.functions);

// This should match the grammar defined in Beancount (`query/query_parser.py`).
const string = /^("[^"]*"|'[^']*')/;
const date = /^(?:#(?:"[^"]*"|'[^']*')|\d\d\d\d-\d\d-\d\d)/;
const decimal = /^[-+]?([0-9]+\.[0-9]*|[0-9]*\.[0-9]+)/;
const integer = /^[-+]?[0-9]+/;

// Check for matches - convert the response of StringStream.match into a boolean explicitly
const m = (s: StringStream, p: RegExp) => {
  const match = s.match(p);
  return match != null && match !== false;
};

const consume_block_comment = (
  stream: StringStream,
  state: BqlParserState,
): string => {
  const end = stream.string.indexOf("*/", stream.pos);
  if (end === -1) {
    stream.skipToEnd();
  } else {
    stream.pos = end + 2;
    state.block_comment = false;
  }
  return "comment";
};

export const bql_stream_parser: StreamParser<BqlParserState> = {
  startState: () => ({ block_comment: false, terminated: false }),
  token(stream, state) {
    if (state.terminated) {
      stream.skipToEnd();
      return "comment";
    }
    if (state.block_comment) {
      return consume_block_comment(stream, state);
    }
    if (stream.eatSpace() || stream.eol()) {
      return null;
    }
    const block_comment = stream.match("/*");
    if (block_comment !== null && block_comment !== false) {
      state.block_comment = true;
      return consume_block_comment(stream, state);
    }
    if (stream.eat(";") !== undefined) {
      state.terminated = true;
      stream.skipToEnd();
      return "comment";
    }
    if (m(stream, string)) {
      return "string";
    }
    if (m(stream, date) || m(stream, decimal) || m(stream, integer)) {
      return "number";
    }
    if (m(stream, /\w+/)) {
      const word = stream.current().toLowerCase();
      if (keywords.has(word)) {
        return "keyword";
      }
      if (columns.has(word)) {
        return "typeName";
      }
      if (functions.has(word) && stream.peek() === "(") {
        return "macroName";
      }
      return "name";
    }
    // Skip one character since no known token matched.
    const char = stream.next();
    if (char === "*") {
      return "typeName";
    }
    return null;
  },
};
