name: Deploy testing environment to EC2

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      Fava_image_tag: ${{ steps.docker_image_build.outputs.tag }}

    steps:
      - name: Checkout repository (ahdsab/Fava)
        uses: actions/checkout@v4

      - name: Build and push Docker image
        id: docker_image_build
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

          # Use short commit SHA (first 7 characters)
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          TAG="${SHORT_SHA}-$(date +%Y%m%d-%H%M%S)"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

          sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fava:$TAG .

          sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/fava:$TAG

          # Save the tag for later steps
          echo "FAVA_IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FAVA_EC2_HOST_IP }}
          username: ubuntu
          key: ${{ secrets.Fava_EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            sudo docker run --rm -p 5001:5000 ${{ secrets.DOCKERHUB_USERNAME }}/fava:${{ env.FAVA_IMAGE_TAG }}
