# .github/workflows/ui-testing.yml
name: Selenium UI Tests

on: 
  pull_request:
    branches:
     - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test against'
        required: true
        default: 'staging'
        type: choice
        options:
          - development
          - staging
          - production
      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'chrome'
        type: choice
        options:
        - chrome
        - firefox

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1  # Fetch only the latest commit to speed up the checkout process
        repository: ahdsab/FavaTesting
        token: ${{ secrets.UI_TESTING_GITHUB_TOKEN }}  # Use the token to access the repo

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies  
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run Selenium tests
      env:
        HEADLESS: true
        OLLAMA_URL: http://EC2_PUBLIC_IP:3000
      run: |
        pytest tests/ -v

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1  # Fetch only the latest commit to speed up the checkout process
        repository: your-username/your-ui-testing-repo  # Replace with your UI testing repo
        token: ${{ secrets.UI_TESTING_GITHUB_TOKEN }}  # Use the token to access the repo
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Run Selenium tests
      env:
        HEADLESS: true
        Fava_URL: http://54.73.240.131:5000/example-beancount-file/income_statement/
      run: |
        pytest UI_Testing/ -v